<?php

return [
    '@PSR12' => true,

    'align_multiline_comment' => true,
    'array_indentation' => true,
    'array_syntax' => true,
    'binary_operator_spaces' => true,
    'blank_line_before_statement' => true,
    'braces' => ['allow_single_line_anonymous_class_with_empty_body' => true],
    'cast_spaces' => true,
    'class_attributes_separation' => ['elements' => ['method' => 'one', 'property' => 'one']],
    'class_definition' => ['single_line' => true, 'inline_constructor_arguments' => true],
    'class_reference_name_casing' => true,
    'clean_namespace' => true,
    'concat_space' => true,
    'control_structure_continuation_position' => true,
    'declare_parentheses' => true,
    'dir_constant' => true,
    'explicit_indirect_variable' => true,
    'explicit_string_variable' => true,
    'fopen_flag_order' => true,
    'fully_qualified_strict_types' => true,
    'function_typehint_space' => true,
    'global_namespace_import' => true,
    'heredoc_to_nowdoc' => true,
    'implode_call' => true,
    'include' => true,
    'integer_literal_case' => true,
    'lambda_not_used_import' => true,
    'linebreak_after_opening_tag' => true,
    'list_syntax' => ['syntax' => 'short'],
    'magic_constant_casing' => true,
    'magic_method_casing' => true,
    'method_argument_space' => ['after_heredoc' => true, 'on_multiline' => 'ignore'],
    'method_chaining_indentation' => true,
    'modernize_types_casting' => true,
    'multiline_comment_opening_closing' => true,
    'multiline_whitespace_before_semicolons' => true,
    'native_function_casing' => true,
    'native_function_type_declaration_casing' => true,
    'no_alias_functions' => ['sets' => ['@all']],
    'no_binary_string' => true,
    'no_blank_lines_after_phpdoc' => true,
    'no_empty_phpdoc' => true,
    'no_empty_statement' => true,
    'no_extra_blank_lines' => true,
    'no_leading_namespace_whitespace' => true,
    'no_mixed_echo_print' => true,
    'no_null_property_initialization' => true,
    'no_php4_constructor' => true,
    'no_short_bool_cast' => true,
    'no_singleline_whitespace_before_semicolons' => true,
    'no_spaces_around_offset' => true,
    'no_superfluous_elseif' => true,
    'no_trailing_comma_in_list_call' => true,
    'no_trailing_comma_in_singleline_array' => true,
    'no_trailing_comma_in_singleline_function_call' => true,
    'no_unneeded_control_parentheses' => true,
    'no_unneeded_curly_braces' => ['namespaces' => true],
    'no_unneeded_final_method' => true,
    'no_unreachable_default_argument_value' => true,
    'no_unset_cast' => true,
    'no_unset_on_property' => true,
    'no_unused_imports' => true,
    'no_useless_else' => true,
    'no_useless_return' => true,
    'no_useless_sprintf' => true,
    'no_whitespace_before_comma_in_array' => true,
    'no_whitespace_in_blank_line' => true,
    'normalize_index_brace' => true,
    'not_operator_with_successor_space' => true,
    'object_operator_without_whitespace' => true,
    'operator_linebreak' => ['only_booleans' => true],
    'ordered_imports' => ['sort_algorithm' => 'alpha', 'imports_order' => ['class', 'function', 'const']],
    'php_unit_construct' => true,
    'php_unit_fqcn_annotation' => true,
    'php_unit_namespaced' => true,
    'php_unit_set_up_tear_down_visibility' => true,
    'phpdoc_align' => ['align' => 'left', 'tags' => ['param', 'property', 'return', 'throws', 'type', 'var', 'method']],
    'phpdoc_annotation_without_dot' => true,
    'phpdoc_indent' => true,
    'phpdoc_inline_tag_normalizer' => true,
    'phpdoc_line_span' => true,
    'phpdoc_no_access' => true,
    'phpdoc_no_alias_tag' => true,
    'phpdoc_no_package' => true,
    'phpdoc_no_useless_inheritdoc' => true,
    'phpdoc_order' => true,
    'phpdoc_return_self_reference' => true,
    'phpdoc_scalar' => true,
    'phpdoc_separation' => true,
    'phpdoc_single_line_var_spacing' => true,
    'phpdoc_summary' => true,
    'phpdoc_tag_casing' => true,
    'phpdoc_tag_type' => ['tags' => ['inheritDoc' => 'inline']],
    'phpdoc_trim' => true,
    'phpdoc_trim_consecutive_blank_line_separation' => true,
    'phpdoc_types' => true,
    'phpdoc_types_order' => ['null_adjustment' => 'always_last', 'sort_algorithm' => 'none'],
    'phpdoc_var_annotation_correct_order' => true,
    'phpdoc_var_without_name' => true,
    'pow_to_exponentiation' => true,
    'psr_autoloading' => true,
    'return_assignment' => true,
    'self_accessor' => true,
    'self_static_accessor' => true,
    'semicolon_after_instruction' => true,
    'set_type_to_cast' => true,
    'simple_to_complex_string_variable' => true,
    'simplified_if_return' => true,
    'single_class_element_per_statement' => ['elements' => ['const', 'property']],
    'single_line_comment_spacing' => true,
    'single_line_comment_style' => ['comment_types' => ['hash']],
    'single_quote' => true,
    'single_space_after_construct' => true,
    'single_trait_insert_per_statement' => false,
    'space_after_semicolon' => ['remove_in_empty_for_expressions' => true],
    'standardize_not_equals' => true,
    'string_length_to_empty' => true,
    'switch_continue_to_break' => true,
    'ternary_to_null_coalescing' => true,
    'trailing_comma_in_multiline' => true,
    'trim_array_spaces' => true,
    'types_spaces' => true,
    'unary_operator_spaces' => true,
    'whitespace_after_comma_in_array' => true,
];
